export default {
  login: "arshkharbanda2010",
  id: 32016836,
  node_id: "MDQ6VXNlcjMyMDE2ODM2",
  avatar_url: "https://avatars.githubusercontent.com/u/32016836?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/arshkharbanda2010",
  html_url: "https://github.com/arshkharbanda2010",
  followers_url: "https://api.github.com/users/arshkharbanda2010/followers",
  following_url:
    "https://api.github.com/users/arshkharbanda2010/following{/other_user}",
  gists_url: "https://api.github.com/users/arshkharbanda2010/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/arshkharbanda2010/starred{/owner}{/repo}",
  subscriptions_url:
    "https://api.github.com/users/arshkharbanda2010/subscriptions",
  organizations_url: "https://api.github.com/users/arshkharbanda2010/orgs",
  repos_url: "https://api.github.com/users/arshkharbanda2010/repos",
  events_url: "https://api.github.com/users/arshkharbanda2010/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/arshkharbanda2010/received_events",
  type: "User",
  site_admin: false,
  name: "Arshdeep Singh",
  company: null,
  blog: "",
  location: "New Delhi,India",
  email: null,
  hireable: true,
  bio: "Electronics Lover and Hardcore Coder, Infosec Addict, Security Researcher, CTFer, Badminton Champ",
  twitter_username: null,
  public_repos: 157,
  public_gists: 0,
  followers: 10,
  following: 74,
  created_at: "2017-09-16T14:06:15Z",
  updated_at: "2021-09-10T14:46:23Z",
};
