export default [
  {
    login: "sukhbirss",
    id: 70104881,
    node_id: "MDQ6VXNlcjcwMTA0ODgx",
    avatar_url: "https://avatars.githubusercontent.com/u/70104881?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/sukhbirss",
    html_url: "https://github.com/sukhbirss",
    followers_url: "https://api.github.com/users/sukhbirss/followers",
    following_url:
      "https://api.github.com/users/sukhbirss/following{/other_user}",
    gists_url: "https://api.github.com/users/sukhbirss/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/sukhbirss/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/sukhbirss/subscriptions",
    organizations_url: "https://api.github.com/users/sukhbirss/orgs",
    repos_url: "https://api.github.com/users/sukhbirss/repos",
    events_url: "https://api.github.com/users/sukhbirss/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/sukhbirss/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "DiljyotS",
    id: 34857625,
    node_id: "MDQ6VXNlcjM0ODU3NjI1",
    avatar_url: "https://avatars.githubusercontent.com/u/34857625?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/DiljyotS",
    html_url: "https://github.com/DiljyotS",
    followers_url: "https://api.github.com/users/DiljyotS/followers",
    following_url:
      "https://api.github.com/users/DiljyotS/following{/other_user}",
    gists_url: "https://api.github.com/users/DiljyotS/gists{/gist_id}",
    starred_url: "https://api.github.com/users/DiljyotS/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/DiljyotS/subscriptions",
    organizations_url: "https://api.github.com/users/DiljyotS/orgs",
    repos_url: "https://api.github.com/users/DiljyotS/repos",
    events_url: "https://api.github.com/users/DiljyotS/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/DiljyotS/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "GurprasadSingh",
    id: 37959542,
    node_id: "MDQ6VXNlcjM3OTU5NTQy",
    avatar_url: "https://avatars.githubusercontent.com/u/37959542?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/GurprasadSingh",
    html_url: "https://github.com/GurprasadSingh",
    followers_url: "https://api.github.com/users/GurprasadSingh/followers",
    following_url:
      "https://api.github.com/users/GurprasadSingh/following{/other_user}",
    gists_url: "https://api.github.com/users/GurprasadSingh/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/GurprasadSingh/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/GurprasadSingh/subscriptions",
    organizations_url: "https://api.github.com/users/GurprasadSingh/orgs",
    repos_url: "https://api.github.com/users/GurprasadSingh/repos",
    events_url: "https://api.github.com/users/GurprasadSingh/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/GurprasadSingh/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "rodriguesfas",
    id: 5026592,
    node_id: "MDQ6VXNlcjUwMjY1OTI=",
    avatar_url: "https://avatars.githubusercontent.com/u/5026592?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/rodriguesfas",
    html_url: "https://github.com/rodriguesfas",
    followers_url: "https://api.github.com/users/rodriguesfas/followers",
    following_url:
      "https://api.github.com/users/rodriguesfas/following{/other_user}",
    gists_url: "https://api.github.com/users/rodriguesfas/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/rodriguesfas/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/rodriguesfas/subscriptions",
    organizations_url: "https://api.github.com/users/rodriguesfas/orgs",
    repos_url: "https://api.github.com/users/rodriguesfas/repos",
    events_url: "https://api.github.com/users/rodriguesfas/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/rodriguesfas/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "sygops",
    id: 16489082,
    node_id: "MDQ6VXNlcjE2NDg5MDgy",
    avatar_url: "https://avatars.githubusercontent.com/u/16489082?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/sygops",
    html_url: "https://github.com/sygops",
    followers_url: "https://api.github.com/users/sygops/followers",
    following_url: "https://api.github.com/users/sygops/following{/other_user}",
    gists_url: "https://api.github.com/users/sygops/gists{/gist_id}",
    starred_url: "https://api.github.com/users/sygops/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/sygops/subscriptions",
    organizations_url: "https://api.github.com/users/sygops/orgs",
    repos_url: "https://api.github.com/users/sygops/repos",
    events_url: "https://api.github.com/users/sygops/events{/privacy}",
    received_events_url: "https://api.github.com/users/sygops/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "dostonhamrakulov",
    id: 29751357,
    node_id: "MDQ6VXNlcjI5NzUxMzU3",
    avatar_url: "https://avatars.githubusercontent.com/u/29751357?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/dostonhamrakulov",
    html_url: "https://github.com/dostonhamrakulov",
    followers_url: "https://api.github.com/users/dostonhamrakulov/followers",
    following_url:
      "https://api.github.com/users/dostonhamrakulov/following{/other_user}",
    gists_url: "https://api.github.com/users/dostonhamrakulov/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/dostonhamrakulov/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/dostonhamrakulov/subscriptions",
    organizations_url: "https://api.github.com/users/dostonhamrakulov/orgs",
    repos_url: "https://api.github.com/users/dostonhamrakulov/repos",
    events_url:
      "https://api.github.com/users/dostonhamrakulov/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/dostonhamrakulov/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "peterkoncz",
    id: 31049172,
    node_id: "MDQ6VXNlcjMxMDQ5MTcy",
    avatar_url: "https://avatars.githubusercontent.com/u/31049172?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/peterkoncz",
    html_url: "https://github.com/peterkoncz",
    followers_url: "https://api.github.com/users/peterkoncz/followers",
    following_url:
      "https://api.github.com/users/peterkoncz/following{/other_user}",
    gists_url: "https://api.github.com/users/peterkoncz/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/peterkoncz/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/peterkoncz/subscriptions",
    organizations_url: "https://api.github.com/users/peterkoncz/orgs",
    repos_url: "https://api.github.com/users/peterkoncz/repos",
    events_url: "https://api.github.com/users/peterkoncz/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/peterkoncz/received_events",
    type: "User",
    site_admin: false,
  },

  {
    login: "verejava",
    id: 39612290,
    node_id: "MDQ6VXNlcjM5NjEyMjkw",
    avatar_url: "https://avatars.githubusercontent.com/u/39612290?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/verejava",
    html_url: "https://github.com/verejava",
    followers_url: "https://api.github.com/users/verejava/followers",
    following_url:
      "https://api.github.com/users/verejava/following{/other_user}",
    gists_url: "https://api.github.com/users/verejava/gists{/gist_id}",
    starred_url: "https://api.github.com/users/verejava/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/verejava/subscriptions",
    organizations_url: "https://api.github.com/users/verejava/orgs",
    repos_url: "https://api.github.com/users/verejava/repos",
    events_url: "https://api.github.com/users/verejava/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/verejava/received_events",
    type: "User",
    site_admin: false,
  },

  {
    login: "SGKOMBE",
    id: 49944531,
    node_id: "MDQ6VXNlcjQ5OTQ0NTMx",
    avatar_url: "https://avatars.githubusercontent.com/u/49944531?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/SGKOMBE",
    html_url: "https://github.com/SGKOMBE",
    followers_url: "https://api.github.com/users/SGKOMBE/followers",
    following_url:
      "https://api.github.com/users/SGKOMBE/following{/other_user}",
    gists_url: "https://api.github.com/users/SGKOMBE/gists{/gist_id}",
    starred_url: "https://api.github.com/users/SGKOMBE/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/SGKOMBE/subscriptions",
    organizations_url: "https://api.github.com/users/SGKOMBE/orgs",
    repos_url: "https://api.github.com/users/SGKOMBE/repos",
    events_url: "https://api.github.com/users/SGKOMBE/events{/privacy}",
    received_events_url: "https://api.github.com/users/SGKOMBE/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jassicajain",
    id: 48386224,
    node_id: "MDQ6VXNlcjQ4Mzg2MjI0",
    avatar_url: "https://avatars.githubusercontent.com/u/48386224?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jassicajain",
    html_url: "https://github.com/jassicajain",
    followers_url: "https://api.github.com/users/jassicajain/followers",
    following_url:
      "https://api.github.com/users/jassicajain/following{/other_user}",
    gists_url: "https://api.github.com/users/jassicajain/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/jassicajain/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jassicajain/subscriptions",
    organizations_url: "https://api.github.com/users/jassicajain/orgs",
    repos_url: "https://api.github.com/users/jassicajain/repos",
    events_url: "https://api.github.com/users/jassicajain/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/jassicajain/received_events",
    type: "User",
    site_admin: false,
  },
];
